# Generated by Django 4.1.7 on 2023-06-08 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Arena',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('toztash_joyi', models.BooleanField(default=False)),
                ('dush', models.BooleanField(default=False)),
                ('orindiq', models.BooleanField(default=False)),
                ('ochish_vaqti', models.TimeField()),
                ('yopish_vaqti', models.TimeField()),
                ('trener', models.CharField(max_length=255)),
                ('bio', models.TextField(max_length=255)),
                ('oxirgi_tamir', models.DateField()),
                ('maydon', models.TextField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Sport_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('img', models.ImageField(upload_to='sport_type/')),
            ],
        ),
        migrations.CreateModel(
            name='Viloyat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Shaxar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=255)),
                ('viloyat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.viloyat')),
            ],
        ),
        migrations.CreateModel(
            name='Img',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='arena/')),
                ('arena', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='main.arena')),
            ],
        ),
        migrations.AddField(
            model_name='arena',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.shaxar'),
        ),
        migrations.AddField(
            model_name='arena',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.sport_type'),
        ),
    ]
